### ISSUE TITLE
Skip the first heading

### ISSUE THREAD

**Issue by rnc** [dohliam/tocdown#6]
I would like to be able to skip the first heading, or only search for headings after the `<!-- TocDown Begin -->` markers. I am using the following command line:
```
ruby toc.rb -b -t -m -r -d 3 <file>
```
Essentially this would allow me to format and regenerate contents for repositories that have markdown files such as https://github.com/release-engineering/pom-manipulation-ext

**Comment by dohliam** [comment]
@rnc If you just want to skip the first level heading (i.e., H1), you can do that by removing the `-t` option from your command. This is actually how the table of contents for this repository is generated. You only need to include the `-t` option if you explicitly **want** to include the first heading.

**Comment by rnc** [comment]
@dohliam Thanks for the reply. For the example repository I gave above excluding `-t` doesn't work because then all the first level headings are excluded. I realise I _could_ refactor to use H1 .. H2 format - equally the ability to only search after the markers would work nicely for me

**Comment by dohliam** [comment]
@rnc Ah I see what you mean now -- I didn't notice that you had multiple H1s in that file. As far as I know this is not standard though since H1 is supposed to be for the document title, and first-level headings would then use H2. So the easiest thing to do, as you suggested, would be to just bump the headings up one level in the file itself.

The idea of being able to specifically ignore headings before the toc markers is interesting though, and I can see how that could be useful more generally. If you (or anyone else) might be interested in a PR to enable that I'd be happy to merge it!

**Comment by rnc** [comment]
@dohliam Cool, I've given it a go in #7 - I've never tried Ruby before so review welcome! :-)

**Comment by rnc** [comment]
Fixed by #7
